services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    stop_grace_period: 30s
    image: ghcr.io/blakeblackshear/frigate:0.15.0
    shm_size: "512mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate:/config
      - frigate_storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    #security_opt:
    #  - apparmor=unconfined
    #  - systempaths=unconfined
    ports:
      - "8971:8971"
      # - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "127.0.0.1:5000:5000"
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
    networks:
      - nvr-network


  mosquitto:
    image: eclipse-mosquitto:2.0.20
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "127.0.0.1:1883:1883"
      - "127.0.0.1:9001:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - nvr-network

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:2024.12.0"
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  ntp:
    build: ntp
    #image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
        - 123:123/udp
    environment:
        - NTP_SERVERS=pool.ntp.org
        - LOG_LEVEL=0

networks:
  nvr-network:
    driver: bridge

volumes:
  frigate_storage:
    driver: local
